# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
prost = "0.12.1"
prost-types = "0.12.1"
tonic = "0.10.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
tracing-actix-web = "0.7.8"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"]}

[workspace]
members = ["storage", "common", "kvstore"]
resolver = "2"