# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
prost = "0.12.1"
prost-types = "0.12.1"
tonic = "0.10.2"

[workspace]
members = ["storage", "common", "kvstore"]
resolver = "2"